### PR TITLE
Support font-kerning

### PR DESCRIPTION
**Pull request by marek-saji**
In addition to font-variant-*, support font-kerning.

### CODE REVIEW

**Comment by MoOx** [comment]
build seems broken on this branch. Can you fix it ?

**Comment by marek-saji** [comment]
> build seems broken on this branch. Can you fix it ?

Sorry about that. Needed rebasing on #3.

**Comment by MoOx** [comment]
Released in 1.1.0

**Comment by marek-saji** [comment]
thanks. and thanks for postcss-variant. {:

**Pull request merged**
